### ISSUE TITLE
pg_rewind with async replication

### ISSUE THREAD

**Issue by MasahikoSawada** [vmware/pg_rewind#15]
Hi all,

Can we use pg_rewind when two server are linked with async replication?
I tried to test with following simple scenario. But failed due to recycle WAL file by the server.

1. Build async replication.
2. kill master postgres process
3. promote standby server to master
4. start old master server
5. stop old master server
6. perform the pg_rewind
 -> it failed and I got following errors.

The servers diverged at WAL position 0/3000000 on timeline 1.
could not open file "data/pg_xlog/000000010000000000000002": No such file or directory
could not previous WAL record at 0/20000F0: (null)

In this case, should we use the wal_keep_segments? or do you have suggestions about that the WAL file will be recycled?

**Comment by michaelpq** [comment]
I guess that wal_keep_segments is one way to go..
