### ISSUE TITLE
How to install pg_rewind in FreeBSD 10.1 

### ISSUE THREAD

**Issue by pshanmu** [vmware/pg_rewind#44]
Hi - 

How to install pg_rewind in FreeBSD 10.1 

I already installed postgresql93-server (from ports)

- Shanmu

**Comment by michaelpq** [comment]
There is no RPM available (contributions welcome from packagers), hence you will need to compile from source the code. Note as well that pg_rewind needs the source code of Postgres to be compiled properly as well, with xlogreader.c.
Last thing: when compiling with 9.3 headers and libraries, be sure to use the branch REL9_3_STABLE.

**Comment by pshanmu** [comment]
Thanks
- Shanmu
