### ISSUE TITLE
Fails with pg_xlog/xlogtemp files

### ISSUE THREAD

**Issue by dev1ant** [vmware/pg_rewind#45]
It happens quite rare but it happens:
```
error reading xlog record: record with zero length at 1/D5000090
unexpected result while fetching remote files: ERROR:  could not open file "pg_xlog/xlogtemp.23056" for reading: No such file or directory

The servers diverged at WAL position 1/D4A081B0 on timeline 174.
Rewinding from Last common checkpoint at 1/D30A5650 on timeline 174
```

It seems that `process_remote_file` does not skip such files and I don't know if it safe to do. 

Since I've caught it with 9.4 I write about it here. But it seems that version in master also does not handle this situation.

**Comment by michaelpq** [comment]
Indeed, it can happen. e11d9a0 should fix this.
