### ISSUE TITLE
Test pg_rewind error 

### ISSUE THREAD

**Issue by qguan-aa** [vmware/pg_rewind#47]
After install and test pg_rewind I got same error like this:
pg_rewind -D /var/lib/postgresql/9.4/slave --source-pgdata='/var/lib/postgresql/9.4/master'  -v
unexpected control file CRC
pg_rewind -D /var/lib/postgresql/9.4/slave --source-server="host=localhost port=5433 user=postgres" -v
connected to remote server
unexpected control file CRC
I have see the code but still do not understand why may cause this error.

**Comment by michaelpq** [comment]
Yeah I can reproduce it. Let me investigate.
