### ISSUE TITLE
pg_rewind make fail

### ISSUE THREAD

**Issue by qguan-aa** [vmware/pg_rewind#48]
postgresql-9.4.1/contrib/pg_rewind# make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -I../../src/interfaces/libpq -I. -I. -I../../src/include -DFRONTEND   -c -o pg_rewind.o pg_rewind.c
pg_rewind.c: In function ‘checkControlFile’:
pg_rewind.c:475:2: error: unknown type name ‘pg_crc32c’
pg_rewind.c:478:2: warning: implicit declaration of function ‘INIT_CRC32C’ [-Wimplicit-function-declaration]
pg_rewind.c:479:2: warning: implicit declaration of function ‘COMP_CRC32C’ [-Wimplicit-function-declaration]
pg_rewind.c:482:2: warning: implicit declaration of function ‘FIN_CRC32C’ [-Wimplicit-function-declaration]
pg_rewind.c:485:2: warning: implicit declaration of function ‘EQ_CRC32C’ [-Wimplicit-function-declaration]
make: *** [pg_rewind.o] Error 1
Is there something wrong with my make env?

**Comment by michaelpq** [comment]
Use the branch REL9_4_STABLE and it will work.
