### ISSUE TITLE
pg_rewind does not work on 9.4

### ISSUE THREAD

**Issue by odessky** [vmware/pg_rewind#51]
Hi.
I was install pg_rewind on both pgsql servers, set to config:
wal_log_hints = on
full_page_writes = on
Restart master with pg_resetxlog

After I try connect from slave to master via pg_rewind, I get this message:
pg_rewind  -D /var/lib/postgresql/9.4/main --source-server="host=master"
target master need to use either data checksums or "wal_log_hints = on".

This is wrong, couse target master have wal_log_hints = on.

**Comment by michaelpq** [comment]
(Edit: I finally looked at the code of pg_resetxlog my memories about it were fuzzy)
How did you use pg_resetxlog? And why do you need it? pg_resetxlog will reset the control data file of the node where it is run, updating at the same time wal_log_hints to false, leading to the error you are seeing. I see no bugs here.

**Comment by alisade** [comment]
same problem here @odessky @michaelpq did you figure out what the problem was? I do not have anything in my configs with xlog in it!

This is the config by the way

https://gist.github.com/alisade/f86e6886a2caeac68053b1e548968158
