### ISSUE TITLE
Install pg_rewind in a postgresql9.4 installation from repositories 

### ISSUE THREAD

**Issue by isaiasanchez** [vmware/pg_rewind#52]
Hi, 

I have postgresql 9.4 installed from YUM repositories and I want to install pg_rewind in that cluster, but I can't find a way to indicate this module the postgres top_srcdir path.

Is there a workaround to solve this issue?

**Comment by isaiasanchez** [comment]
What I did was download the source package of postgresql 9.4.5 same installed by YUM and compile pg_rewind, then I just copy pg_rewind to /usr/pgsql-9.4/bin directory.

Now I have a doubt, If I update postgresql to a coming 9.4.6 for example, do I need to recompile pg_rewind? or this one will work on all 9.4.x sub-versions.

**Comment by michaelpq** [comment]
> Now I have a doubt, If I update postgresql to a coming 9.4.6 for example, do I need to recompile pg_rewind? or this one will work on all 9.4.x sub-versions.

Yeah, downloading the source tarball is necessary, you should as well update PG_CONFIG to point to the one of your installation so as pg_rewind binary will be installed where needed for your distribution. If you can motivate DevrimGunduz on twitter for example to have packages for pg_rewind that would be the most straight-forward way to get things working. He bundles many packages for Postgres and relative community tools, and you are not the first one asking for a RPM of pg_rewind aligned with Postgres 9.4.

> Now I have a doubt, If I update postgresql to a coming 9.4.6 for example, do I need to recompile pg_rewind? or this one will work on all 9.4.x sub-versions.

This will work with all the 9.4.x versions. There is no need to recompile.
