### ISSUE TITLE
Can't make pg_rewind-REL9_4_STABLE on RedHat 6

### ISSUE THREAD

**Issue by MKiesNewbie** [vmware/pg_rewind#53]
Hi,
I am new to postgres and am looking at the pg_rewind utility for our 9.4.5 version of postgres cluster.
I have downloaded the pg_rewind-REL9_4_STABLE and tried putting it in the contrib/pg_rewind directory as told in the readme document.
When I run make I get errors:
Makefile:54: ../../src/Makefile.global: No such file or directory
Makefile:55: /contrib/contrib-global.mk: No such file or directory
make: **\* No rule to make target `/contrib/contrib-global.mk'.  Stop.

I run the make command as root on the Linux system.
Could someone please help me?
Thanks in advance.

**Comment by michaelpq** [comment]
You need to run at least ./configure on the Postgres code tree you took to copy the code of pg_rewind, src/Makefile.global going missing is meaning that.
