### ISSUE TITLE
pg_control file gets truncated by pg_rewind operation 

### ISSUE THREAD

**Issue by subukris** [vmware/pg_rewind#54]
I'm learning to use pg_rewind and got into a scenario when pg_control and few other files got truncated
when pg_rewind enters into an error condition.

_The servers diverged at WAL position 0/3B6A5780 on timeline 1.
Rewinding from Last common checkpoint at 0/3B2B0A20 on timeline 1
**could not open destination file "/var/mps/db_pgsql/data/postgresql.conf": Permission denied**_

The postgresql.conf had only readonly permissions for all users which I have subsequently fixed. However it would be great if instead of corrupting the pg_control file, pg_rewind did a bail out when it doesn't have permissions.

I googled around and found that a similar issue has been raised and patch proposed for this:
https://www.postgresql.org/message-id/20180115072537.GC1724%40paquier.xyz

Can this patch be applied/ported to the 9.4 stable branch?

Thanks and Regards

**Comment by subukris** [comment]
I missed mentioning that I had done a verbose and dry-run and that ran clean which gave me confidence to go ahead and fire the real operation. It would be great if the dry-run warns of the impending permission problem.

**Comment by michaelpq** [comment]
A similar discussion is going on with upstream, for which I have sent a patch:
https://www.postgresql.org/message-id/flat/20180104200633.17004.16377@wrigleys.postgresql.org
So let's see how is shaped the patch integrated with upstream before backporting anything here.

**Comment by michaelpq** [comment]
The conclusion of upthread is to do nothing, so I am just closing this bug.
